name: Publish npm package

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup env
        run: echo "REPOSYTORY_TAG=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
        shell: bash

      - name: Publish
        run: |
          npm ci
          npm --no-git-tag-version version ${{ env.REPOSYTORY_TAG }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}